source 'https://rubygems.org'

gem 'dotenv'
gem 'lita'
gem 'lita-burn-notice'
gem 'lita-karma'
gem 'lita-should-i'
gem 'lita-slack'
gem 'lita-trivia', '1.0.0'
gem 'lita-weather'
gem 'lita-wotd', '1.1.0'
